### ISSUE TITLE
In order for 6sense customers to take advantage of Net New Accounts identified by 6sense, they need a mechanism to convert the new accounts into standard Accounts in SFDC. 

### ISSUE THREAD

**Issue by petehutton** [CodeScience/6sense#1]
**Tasks:**

- [ ] Create custom button (called 'Convert') on list view and detail pages of 6sense New Account Object.
- [ ] Create trigger to start the field conversion when the 'Convert' button is clicked.
- [ ] Create conversion field mapping repository to map the fields during conversion.
- [ ] Create checkbox, called Converted, on 6sense New Account object - default unchecked.
- [ ] Set Converted checkbox to 'checked during the conversion process.
- [ ] Auto create an account ID for each converted 6sense account.
- [ ] Once a new account has been converted to a standard Account, the new Account ID must be populated in the Account ID field of the 6sense account record.
