### ISSUE TITLE
in order to capture the 6sense new accounts in SFDC, we will need to create a custom object.

### ISSUE THREAD

**Issue by petehutton** [CodeScience/6sense#3]
**Tasks:**

- [ ] Create custom object, called 6sense New Company, with fields identified in the 6sense API document.
- [ ] Add Status field to indicate what state the account is in - New, Imported, Duplicate or Invalid.
- [ ] Create picklist with the following values - New, Converted, Duplicate and Invalid.
- [ ] Set object to be available for reports and workflows.

**Comment by petehutton** [comment]
No longer needed.
