### ISSUE TITLE
In order for 6sense integration with SFDC to be successful the API endpoints need to be built

### ISSUE THREAD

**Issue by petehutton** [CodeScience/6sense#4]
**Tasks:**

- [ ] Complete development of Account Score endpoint.
- [ ] Complete development of Contact Score endpoint.
- [ ] Complete development of Lead Score endpoint. 
- [ ] Complete API documentation.
