### ISSUE TITLE
Refactor Batch process and queue mechanism

### ISSUE THREAD

**Issue by petehutton** [CodeScience/6sense#5]
**Tasks:**

- [ ] Refactor the Batch process to use the new API endpoints - Account Scores, Contact Scores, Lead Scores and Company.
- [ ] Refactor field mapping utility to represent the new API and object mapping.
- [ ] Use the field mapping sheets called 6sense / SFDC object field mapping.

**Notes:**
1. Use the following objects for mapping - 
   * 6sense New Company
   * 6sense Account Scores
   * 6sense Contact Scores
   * 6sense Lead Scores
