### ISSUE TITLE
As a 6sense customer I want the ability to mark 6sense New Company records as duplicate records.

### ISSUE THREAD

**Issue by petehutton** [CodeScience/6sense#6]
**Notes:**
In addition to being able to 'import' records into the standard account object, users will also want the ability to mark certain records as duplicates. 

**Tasks:**

- [ ] Create custom button, named ' Duplicate' on the List view and record Detail pages
- [ ] Create VF page to allow for Account ID search for duplicate record
- [ ] Ad Account ID search functionality on the VF page
- [ ] Create 'Save' button on the VF page that allows the user to save the record once the Account ID has been added.
- [ ] Set the 'Status field for the record to 'Duplicate'
